# Generated by Django 5.1.1 on 2024-12-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchaseitem_serial_numbers_purchasereturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='return_code',
            field=models.CharField(default='DEFAULT_CODE', max_length=255),
        ),
    ]
