# Generated by Django 5.1.1 on 2024-12-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_payment_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='payment_stat',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Terms', 'Terms')], default='Cash', max_length=50),
        ),
    ]
