# Generated by Django 5.1.1 on 2024-12-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sales_payment_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitem',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
