# Generated by Django 5.1.1 on 2024-12-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
