# Generated by Django 5.1.1 on 2024-12-05 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_invoice_invoice_number_alter_invoice_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_code', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sales')),
            ],
        ),
    ]
