# Generated by Django 5.1.1 on 2024-11-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_remove_sales_sales_code_alter_sales_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
