# Generated by Django 5.1.1 on 2024-12-05 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturn',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='return_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='sales.sales'),
        ),
    ]
