# Generated by Django 5.1.1 on 2024-12-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_salesreturn_date_alter_salesreturn_return_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturn',
            name='return_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
